name: Code Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
        pip install -r requirements.txt

    - name: Check formatting with Black
      id: black
      run: black . --check
      continue-on-error: true

    - name: Check imports with isort
      id: isort
      run: isort . --check-only --profile black
      continue-on-error: true

    - name: Lint with flake8
      id: flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --statistics
      continue-on-error: true

    - name: Validate Python syntax
      id: syntax
      run: python -m compileall .
      continue-on-error: true

    - name: Send Success Webhook
      if: success()
      run: curl -X GET ${{ secrets.SUCCESS_WEBHOOK_URL }}

    - name: Send Discord Notification
      if: failure() || steps.black.outcome == 'failure' || steps.isort.outcome == 'failure' || steps.flake8.outcome == 'failure' || steps.syntax.outcome == 'failure'
      uses: Ilshidur/action-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: |
          🚨 Code validation failed for ${{ github.repository }}

          Commit: ${{ github.sha }}
          Branch: ${{ github.ref }}
          Author: ${{ github.actor }}

          Check the action for details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}