name: Code Validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      id: flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --statistics
      continue-on-error: true

    - name: Validate Python syntax
      id: syntax
      run: python -m compileall .
      continue-on-error: true

    - name: Send Success Webhook
      if: success() || (steps.flake8.outcome != 'failure' && steps.syntax.outcome != 'failure')
      run: curl -X GET ${{ secrets.SUCCESS_WEBHOOK_URL }}

    - name: Dokploy Deployment
      if: success() || (steps.flake8.outcome != 'failure' && steps.syntax.outcome != 'failure')
      uses: benbristow/dokploy-deploy-action@0.0.1
      with:
        auth_token: ${{ secrets.DOKPLOY_AUTH_TOKEN }}
        application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
        dokploy_url: ${{ secrets.DOKPLOY_URL }}

    - name: Send Discord Notification
      if: failure() || steps.flake8.outcome == 'failure' || steps.syntax.outcome == 'failure'
      run: |
        curl -H "Content-Type: application/json" -X POST ${{ secrets.DISCORD_WEBHOOK }} \
        -d '{
          "embeds": [{
            "title": "❌ Code Validation Failed",
            "description": "The code validation workflow has failed.",
            "color": 15158332,
            "fields": [
              {
                "name": "Repository",
                "value": "${{ github.repository }}",
                "inline": true
              },
              {
                "name": "Branch",
                "value": "${{ github.ref }}",
                "inline": true
              },
              {
                "name": "Author",
                "value": "${{ github.actor }}",
                "inline": true
              },
              {
                "name": "Commit",
                "value": "${{ github.sha }}",
                "inline": false
              }
            ],
            "footer": {
              "text": "Click the title to view details"
            },
            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }]
        }'